#include <magenta/types.h>
#include <magenta/boot/bootdata.h>
#include <magenta/boot/multiboot.h>
#include <magenta/boot/netboot.h>
#include <magenta/compiler.h>
#include <magenta/crashlogger.h>
#include <magenta/hw/usb-audio.h>
#include <magenta/hw/usb-hid.h>
#include <magenta/hw/usb-hub.h>
#include <magenta/hw/usb.h>
#include <magenta/device/device.h>
#include <magenta/device/audio.h>
// #include <magenta/device/audio2.h>
#include <magenta/device/block.h>
#include <magenta/device/bt-hci.h>
#include <magenta/device/console.h>
#include <magenta/device/display.h>
#include <magenta/device/dmctl.h>
#include <magenta/device/ethernet.h>
#include <magenta/device/hidctl.h>
#include <magenta/device/i2c.h>
#include <magenta/device/input.h>
#include <magenta/device/intel-hda.h>
#include <magenta/device/intel-pt.h>
#include <magenta/device/ioctl-wrapper.h>
#include <magenta/device/ioctl.h>
#include <magenta/device/ktrace.h>
#include <magenta/device/midi.h>
#include <magenta/device/pty.h>
#include <magenta/device/ramdisk.h>
#include <magenta/device/rtc.h>
#include <magenta/device/sysinfo.h>
#include <magenta/device/test.h>
#include <magenta/device/tpm.h>
#include <magenta/device/usb.h>
#include <magenta/device/vfs.h>
#include <magenta/device/wlan.h>
#include <magenta/dlfcn.h>
#include <magenta/errors.h>
// #include <magenta/ktrace.h>
// #include <magenta/ktrace-def.h>
#include <magenta/listnode.h>
#include <magenta/mdi.h>
#include <magenta/mtrace.h>
#include <magenta/pixelformat.h>
#include <magenta/process.h>
#include <magenta/processargs.h>
#include <magenta/status.h>
#include <magenta/syscalls/debug.h>
#include <magenta/syscalls/exception.h>
#include <magenta/syscalls/hypervisor.h>
#include <magenta/syscalls/log.h>
#include <magenta/syscalls/object.h>
#include <magenta/syscalls/pci.h>
#include <magenta/syscalls/policy.h>
#include <magenta/syscalls/port.h>
#include <magenta/syscalls/resource.h>
#include <magenta/syscalls/types.h>
#include <magenta/syscalls.h>
#include <magenta/threads.h>
#include <magenta/tls.h>
#include <magenta/syscalls/definitions.h>
